# Конфигурация базы данных
database:
  path: "data/sherlock.db"

# Настройки канала
channel:
  id: -1002032855126  # ID вашего канала

# Настройки администратора
admin:
  chat_id:  5253442052  # Ваш Chat ID

# Интервал проверки (в минутах)
monitor:
  interval: 0.1