# Конфигурация базы данных
database:
  path: "data/sherlock.db"

# Настройки канала
channel:
  id: -100  # ID вашего канала

# Настройки администратора
admin:
  chat_id:  -  # Ваш Chat ID

# Интервал проверки (в минутах)
monitor:
  interval: 0.1
